name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:      # manual trigger
  
permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Update README Stats
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -s -o stats.svg "https://github-readme-stats.vercel.app/api?username=tyy-dev&count_private=true&show_icons=true&theme=dracula&access_token=$GH_TOKEN"
          
          curl -s -o top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs?username=tyy-dev&langs_count=5&layout=compact&theme=dracula&count_private=true&access_token=$GH_TOKEN"

          # Commit & push updated stats
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.svg top-langs.svg
          git commit -m "Update GitHub stats" || echo "No changes"
          git push
